name: Node CI

on: [push,pull_request]

jobs:
  container-job:

    runs-on: ubuntu-latest

    container:
      image:  node:latest

    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: |
        npm install --unsafe-perm
        npm test
      env:
        CI: true
        NODE_ENV: test
